# all-playbooks.yml
# add all playbooks into one bundle
# will run playbooks sequentially
---
  - import_playbook: yum-update.yml
  - import_playbook: install-services.yml
  - import_playbook: setup-app.yml
  - import_playbook: setup-lb.yml
