# install services

---
  - hosts: loadbalancers
    become: true
    vars_files:
    - vars/default.yml

    tasks:
      - name: Installing apache
        yum: name=httpd state=present
      - name: Ensure apache is started
        service: name=httpd state=started enabled=yes

  - hosts: webservers
    become: true
    vars_files:
      - vars/default.yml

    tasks:
      - name: Installing services
        yum:
          name:
            - httpd
            - php
          state: present
      - name: Ensure apache is started
        service: name=httpd state=started enabled=yes