# yum update

---
  - hosts: webservers:loadbalancers
    become: true
    
    vars_files:
    - vars/default.yml

    tasks:
      - name: Update yum packages
        yum: 
          name: '*' 
          state: latest